export const KEY_VALUES = {SPACE_BAR: 32, LEFT_ARROW: 37, RIGHT_ARROW: 39}
export const UP_ARROW = 38
export const DOWN_ARROW = 40

export const BOARD_WIDTH = 10000
export const SCREEN_HEIGHT = 600
export const SCREEN_WIDTH = 1000
export const GROUND_HEIGHT = 100

export const PLAYER_SPRITE = 'player-sprite'
export const PLAYER_SPRITE_HEIGHT = 60
export const PLAYER_SPRITESHEET = 'player-spritesheet'
export const PLAYER_SPRITESHEET_FRAMES = 9

export const ENEMY_1 = 'enemy-1-sprite'
export const ENEMY_SPRITE_HEIGHT = 40
export const ENEMY_SPRITESHEET = 'enemy-spritesheet'
export const ENEMY_SPRITESHEET_FRAMES = 3

export const GAMEBOARD_WRAPPER = 'gameboard-wrapper'
export const GAMEBOARD_GROUND_1 = 'gameboard-ground-1'
export const GAMEBOARD_GROUND_2 = 'gameboard-ground-2'
export const GAMEBOARD_GROUND_3 = 'gameboard-ground-3'
export const GAMEBOARD_GROUND_4 = 'gameboard-ground-4'

export const CLOUDS_1_SPRITE = 'clouds-1-sprite'
export const CLOUDS_2_SPRITE = 'clouds-2-sprite'
export const CLOUDS_3_SPRITE = 'clouds-3-sprite'
export const CLOUDS_4_SPRITE = 'clouds-4-sprite'
export const CLOUDS_5_SPRITE = 'clouds-5-sprite'
export const CLOUDS_6_SPRITE = 'clouds-6-sprite'

export const BUSH_1_SPRITE_1 = 'bush-1-sprite-1'
export const BUSH_1_SPRITE_2 = 'bush-1-sprite-2'
export const BUSH_1_SPRITE_3 = 'bush-1-sprite-3'
export const BUSH_1_SPRITE_4 = 'bush-1-sprite-4'
export const BUSH_1_SPRITE_5 = 'bush-1-sprite-5'
export const BUSH_1_SPRITE_6 = 'bush-1-sprite-6'
export const BUSH_1_SPRITE_7 = 'bush-1-sprite-7'
export const BUSH_1_SPRITE_8 = 'bush-1-sprite-8'
export const BUSH_1_SPRITE_9 = 'bush-1-sprite-9'

export const BUSH_2_SPRITE_1 = 'bush-2-sprite-1'
export const BUSH_2_SPRITE_2 = 'bush-2-sprite-2'
export const BUSH_2_SPRITE_3 = 'bush-2-sprite-3'
export const BUSH_2_SPRITE_4 = 'bush-2-sprite-4'
export const BUSH_2_SPRITE_5 = 'bush-2-sprite-5'
export const BUSH_2_SPRITE_6 = 'bush-2-sprite-6'
export const BUSH_2_SPRITE_7 = 'bush-2-sprite-7'

export const BOX_SPRITE_1 = 'box-sprite-1'
export const BOX_SPRITE_2 = 'box-sprite-2'
export const BOX_SPRITE_3 = 'box-sprite-3'
export const BOX_SPRITE_4 = 'box-sprite-4'
export const BOX_SPRITE_5 = 'box-sprite-5'
export const BOX_SPRITE_6 = 'box-sprite-6'
export const BOX_SPRITE_7 = 'box-sprite-7'
export const BOX_SPRITE_8 = 'box-sprite-8'
export const BOX_SPRITE_9 = 'box-sprite-9'
export const BOX_SPRITE_10 = 'box-sprite-10'
export const BOX_SPRITE_11 = 'box-sprite-11'
export const BOX_SPRITE_12 = 'box-sprite-12'
export const BOX_SPRITE_13 = 'box-sprite-13'
export const BOX_SPRITE_14 = 'box-sprite-14'
export const BOX_SPRITE_15 = 'box-sprite-15'
export const BOX_SPRITE_16 = 'box-sprite-16'
export const BOX_SPRITE_17 = 'box-sprite-17'
export const BOX_SPRITE_18 = 'box-sprite-18'
export const BOX_SPRITE_19 = 'box-sprite-19'
export const BOX_SPRITE_20 = 'box-sprite-20'
export const BOX_SPRITE_21 = 'box-sprite-21'
export const BOX_SPRITE_22 = 'box-sprite-22'
export const BOX_SPRITE_23 = 'box-sprite-23'
export const BOX_SPRITE_24 = 'box-sprite-24'
export const BOX_SPRITE_25 = 'box-sprite-25'
export const BOX_SPRITE_26 = 'box-sprite-26'
export const BOX_SPRITE_27 = 'box-sprite-27'
export const BOX_SPRITE_28 = 'box-sprite-28'
export const BOX_SPRITE_29 = 'box-sprite-29'
export const BOX_SPRITE_30 = 'box-sprite-30'
export const BOX_SPRITE_31 = 'box-sprite-31'
export const BOX_SPRITE_32 = 'box-sprite-32'
export const BOX_SPRITE_33 = 'box-sprite-33'
export const BOX_SPRITE_34 = 'box-sprite-34'
export const BOX_SPRITE_35 = 'box-sprite-35'
export const BOX_SPRITE_36 = 'box-sprite-36'
export const BOX_SPRITE_37 = 'box-sprite-37'
export const BOX_SPRITE_38 = 'box-sprite-38'
export const BOX_SPRITE_39 = 'box-sprite-39'
export const BOX_SPRITE_40 = 'box-sprite-40'
export const BOX_SPRITE_41 = 'box-sprite-41'
export const BOX_SPRITE_42 = 'box-sprite-42'
export const BOX_SPRITE_43 = 'box-sprite-43'
export const BOX_SPRITE_44 = 'box-sprite-44'
export const BOX_SPRITE_45 = 'box-sprite-45'
export const BOX_SPRITE_46 = 'box-sprite-46'
export const BOX_SPRITE_47 = 'box-sprite-47'
export const BOX_SPRITE_48 = 'box-sprite-48'
export const BOX_SPRITE_49 = 'box-sprite-49'
export const BOX_SPRITE_50 = 'box-sprite-50'
export const BOX_SPRITE_51 = 'box-sprite-51'
export const BOX_SPRITE_52 = 'box-sprite-52'
export const BOX_SPRITE_53 = 'box-sprite-53'
export const BOX_SPRITE_54 = 'box-sprite-54'
export const BOX_SPRITE_55 = 'box-sprite-55'
export const BOX_SPRITE_56 = 'box-sprite-56'
export const BOX_SPRITE_57 = 'box-sprite-57'
export const BOX_SPRITE_58 = 'box-sprite-58'
export const BOX_SPRITE_59 = 'box-sprite-59'
export const BOX_SPRITE_60 = 'box-sprite-60'
export const BOX_SPRITE_61 = 'box-sprite-61'
export const BOX_SPRITE_62 = 'box-sprite-62'
export const BOX_SPRITE_63 = 'box-sprite-63'
export const BOX_SPRITE_64 = 'box-sprite-64'
export const BOX_SPRITE_65 = 'box-sprite-65'
export const BOX_SPRITE_66 = 'box-sprite-66'
export const BOX_SPRITE_67 = 'box-sprite-67'
export const BOX_SPRITE_68 = 'box-sprite-68'
export const BOX_SPRITE_69 = 'box-sprite-69'
export const BOX_SPRITE_70 = 'box-sprite-70'

export const PLAYER_MOVEMENT_SPEED = 5
export const PLAYER_JUMP_MOVEMENT_SPEED = 4
export const PLAYER_MAX_JUMP_HEIGHT = 100
export const PLAYER_MAX_JUMP_HEIGHT_HOLDING_SPACE = PLAYER_MAX_JUMP_HEIGHT * 1.5
export const SYNC_SPEED = 16 // to achieve 60 fps
export const CLOUD_1_SPEED = 0.4
export const CLOUD_2_SPEED = 0.3
export const CLOUD_3_SPEED = 0.2
export const ANIMATION_SPEED = SYNC_SPEED * 4
